In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("AMEDAS-54166")

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 18 columns):
HEAD:DateTime    13 non-null int64
CONTXT-ID        13 non-null object
LAT              13 non-null float64
LON              13 non-null float64
ObsTemp          13 non-null float64
ObsPrec1h        13 non-null int64
ObsRH            13 non-null int64
ObsDewTemp       13 non-null int64
ObsWndSpd        13 non-null float64
ObsWndDir        13 non-null int64
ObsGustSpd       13 non-null float64
ObsGustDir       13 non-null int64
ObsSnowDpt       13 non-null int64
ObsSnowDif       13 non-null int64
ObsSnowFall      13 non-null int64
ObsSilTemp       13 non-null int64
ObsBrgTemp       13 non-null int64
ObsVis           13 non-null int64
dtypes: float64(5), int64(12), object(1)
memory usage: 1.9+ KB

In [5]:
data.head()

,HEAD:DateTime,CONTXT-ID,LAT,LON,ObsTemp,ObsPrec1h,ObsRH,ObsDewTemp,ObsWndSpd,ObsWndDir,ObsGustSpd,ObsGustDir,ObsSnowDpt,ObsSnowDif,ObsSnowFall,ObsSilTemp,ObsBrgTemp,ObsVis
0,201906230000,AMEDAS-54166,38.07,138.44,22.6,0,-9999,-9999,8.2,9,9.7,10,-9999,-9999,-9999,-9999,-9999,-9999
1,201906230000,AMEDAS-54166,38.07,138.44,22.6,0,-9999,-9999,8.2,9,9.7,10,-9999,-9999,-9999,-9999,-9999,-9999
2,201906230010,AMEDAS-54166,38.07,138.44,22.7,0,-9999,-9999,8.1,9,10.3,9,-9999,-9999,-9999,-9999,-9999,-9999
3,201906230010,AMEDAS-54166,38.07,138.44,22.7,0,-9999,-9999,8.1,9,10.3,9,-9999,-9999,-9999,-9999,-9999,-9999
4,201906230020,AMEDAS-54166,38.07,138.44,22.7,0,-9999,-9999,8.4,9,10.8,10,-9999,-9999,-9999,-9999,-9999,-9999

In [9]:
data[data["HEAD:DateTime"]==201906230000]

,HEAD:DateTime,CONTXT-ID,LAT,LON,ObsTemp,ObsPrec1h,ObsRH,ObsDewTemp,ObsWndSpd,ObsWndDir,ObsGustSpd,ObsGustDir,ObsSnowDpt,ObsSnowDif,ObsSnowFall,ObsSilTemp,ObsBrgTemp,ObsVis
0,201906230000,AMEDAS-54166,38.07,138.44,22.6,0,-9999,-9999,8.2,9,9.7,10,-9999,-9999,-9999,-9999,-9999,-9999
1,201906230000,AMEDAS-54166,38.07,138.44,22.6,0,-9999,-9999,8.2,9,9.7,10,-9999,-9999,-9999,-9999,-9999,-9999
12,201906230000,AMEDAS-54166,38.07,138.44,22.6,0,-9999,-9999,8.2,9,9.7,10,-9999,-9999,-9999,-9999,-9999,-9999

In [18]:
data1 = pd.DataFrame()

In [19]:
data1

Empty DataFrame
Columns: []
Index: []

In [34]:
data1 = pd.DataFrame()
for i in data.index:
    if data.loc[i,"HEAD:DateTime"]%100 == 0:
        print(i)
        data1 = data1.append(pd.Series(data.loc[i,:]), ignore_index = True)
    #print(data.loc[i,"HEAD:DateTime"])

0
1
12

In [35]:
data1

,CONTXT-ID,HEAD:DateTime,LAT,LON,ObsBrgTemp,ObsDewTemp,ObsGustDir,ObsGustSpd,ObsPrec1h,ObsRH,ObsSilTemp,ObsSnowDif,ObsSnowDpt,ObsSnowFall,ObsTemp,ObsVis,ObsWndDir,ObsWndSpd
0,AMEDAS-54166,2.019062e+11,38.07,138.44,-9999.0,-9999.0,10.0,9.7,0.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,22.6,-9999.0,9.0,8.2
1,AMEDAS-54166,2.019062e+11,38.07,138.44,-9999.0,-9999.0,10.0,9.7,0.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,22.6,-9999.0,9.0,8.2
2,AMEDAS-54166,2.019062e+11,38.07,138.44,-9999.0,-9999.0,10.0,9.7,0.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,22.6,-9999.0,9.0,8.2